### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Nodorfsc2** [tnoiret/ObjectCodeExporter#1]
Hi,

On the initialisation of List, there is not ";" at the end.
Example :
list = new List<Guid>()
instead of
list = new List<Guid>();

For the flag enum with more than one value, the syntax is not correct :
Nature = NatureEnum.Nature1, Nature2, Nature3;
instead of
Nature = NatureEnum.Nature1 | NatureEnum.Nature2 | NatureEnum.Nature3;

**Comment by tnoiret** [comment]
Fix with last chekin
